import "server-only"

export const search = async (opts: {
  take?: number
  skip?: number
  orderBy?: any
  cacheStrategy?: any
}) => {
  return [
  "Aspirin, also known as CHEMBL25, is a small molecule that was first approved in 1950. It has a molecular weight of 180.16 and a monoisotopic weight of 180.0423. Aspirin is classified as an acid with 3 hydrogen bond acceptors and 1 hydrogen bond donor. It has a polar surface area of 63.60 and 2 rotatable bonds. the compound has 0 violations of Lipinski's rule of five. Aspirin has a molecular formula of C9H804 and a canonical SMILES notation of CC(=0)0c1ccccc1c(=0)0.",
  "Aspirin, also known as CHEMBL25, is a small molecule that was first approved in 1950. It has a molecular weight of 180.16 and a monoisotopic weight of 180.0423. Aspirin is classified as an acid with 3 hydrogen bond acceptors and 1 hydrogen bond donor. It has a polar surface area of 63.60 and 2 rotatable bonds. the compound has 0 violations of Lipinski's rule of five. Aspirin has a molecular formula of C9H804 and a canonical SMILES notation of CC(=0)0c1ccccc1c(=0)0.",
  "Aspirin, also known as CHEMBL25, is a small molecule that was first approved in 1950. It has a molecular weight of 180.16 and a monoisotopic weight of 180.0423. Aspirin is classified as an acid with 3 hydrogen bond acceptors and 1 hydrogen bond donor. It has a polar surface area of 63.60 and 2 rotatable bonds. the compound has 0 violations of Lipinski's rule of five. Aspirin has a molecular formula of C9H804 and a canonical SMILES notation of CC(=0)0c1ccccc1c(=0)0.",
  "Aspirin, also known as CHEMBL25, is a small molecule that was first approved in 1950. It has a molecular weight of 180.16 and a monoisotopic weight of 180.0423. Aspirin is classified as an acid with 3 hydrogen bond acceptors and 1 hydrogen bond donor. It has a polar surface area of 63.60 and 2 rotatable bonds. the compound has 0 violations of Lipinski's rule of five. Aspirin has a molecular formula of C9H804 and a canonical SMILES notation of CC(=0)0c1ccccc1c(=0)0.",
  "Aspirin, also known as CHEMBL25, is a small molecule that was first approved in 1950. It has a molecular weight of 180.16 and a monoisotopic weight of 180.0423. Aspirin is classified as an acid with 3 hydrogen bond acceptors and 1 hydrogen bond donor. It has a polar surface area of 63.60 and 2 rotatable bonds. the compound has 0 violations of Lipinski's rule of five. Aspirin has a molecular formula of C9H804 and a canonical SMILES notation of CC(=0)0c1ccccc1c(=0)0.",
  "Aspirin, also known as CHEMBL25, is a small molecule that was first approved in 1950. It has a molecular weight of 180.16 and a monoisotopic weight of 180.0423. Aspirin is classified as an acid with 3 hydrogen bond acceptors and 1 hydrogen bond donor. It has a polar surface area of 63.60 and 2 rotatable bonds. the compound has 0 violations of Lipinski's rule of five. Aspirin has a molecular formula of C9H804 and a canonical SMILES notation of CC(=0)0c1ccccc1c(=0)0.",
  "Aspirin, also known as CHEMBL25, is a small molecule that was first approved in 1950. It has a molecular weight of 180.16 and a monoisotopic weight of 180.0423. Aspirin is classified as an acid with 3 hydrogen bond acceptors and 1 hydrogen bond donor. It has a polar surface area of 63.60 and 2 rotatable bonds. the compound has 0 violations of Lipinski's rule of five. Aspirin has a molecular formula of C9H804 and a canonical SMILES notation of CC(=0)0c1ccccc1c(=0)0.",
  "Aspirin, also known as CHEMBL25, is a small molecule that was first approved in 1950. It has a molecular weight of 180.16 and a monoisotopic weight of 180.0423. Aspirin is classified as an acid with 3 hydrogen bond acceptors and 1 hydrogen bond donor. It has a polar surface area of 63.60 and 2 rotatable bonds. the compound has 0 violations of Lipinski's rule of five. Aspirin has a molecular formula of C9H804 and a canonical SMILES notation of CC(=0)0c1ccccc1c(=0)0.",
  "Aspirin, also known as CHEMBL25, is a small molecule that was first approved in 1950. It has a molecular weight of 180.16 and a monoisotopic weight of 180.0423. Aspirin is classified as an acid with 3 hydrogen bond acceptors and 1 hydrogen bond donor. It has a polar surface area of 63.60 and 2 rotatable bonds. the compound has 0 violations of Lipinski's rule of five. Aspirin has a molecular formula of C9H804 and a canonical SMILES notation of CC(=0)0c1ccccc1c(=0)0.",
  "Aspirin, also known as CHEMBL25, is a small molecule that was first approved in 1950. It has a molecular weight of 180.16 and a monoisotopic weight of 180.0423. Aspirin is classified as an acid with 3 hydrogen bond acceptors and 1 hydrogen bond donor. It has a polar surface area of 63.60 and 2 rotatable bonds. the compound has 0 violations of Lipinski's rule of five. Aspirin has a molecular formula of C9H804 and a canonical SMILES notation of CC(=0)0c1ccccc1c(=0)0.",
  ]
}
