---
# Source: search-server/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # Needed to grant your app an access to AWS resources
    eks.amazonaws.com/role-arn: "arn:aws:iam::6.98471419283e+11:role/search-server-k8s-service-iam-role"
  name: search-server
  namespace: dev
---
# Source: search-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: search-server
  namespace: dev
spec:
  ports:
    - port: 3030
      targetPort: 3030
      protocol: TCP
  selector:
    app: search-server
  sessionAffinity: "ClientIP"
---
# Source: search-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: search-server
  name: search-server
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: search-server
    spec:
      containers:
      - env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: DB_USERNAME
              name: search-server
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: search-server
        - name: DB_HOST
          value: curieo-db-1.cjgu6u6kc9e8.eu-central-1.rds.amazonaws.com
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: curieo
        - name: DB
          value: postgresql://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/${DB_NAME}
        image: 698471419283.dkr.ecr.eu-central-1.amazonaws.com/curieo-search-server:1.0
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 3030
            protocol: TCP
        name: search-server
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 1
            memory: 512Mi
---
# Source: search-server/templates/AuthPolicy.yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: search-server-rule-policy
  namespace: dev
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            ipBlocks:
              - "*"
      to:
        - operation:
            hosts:
              - search-server.dev.curieo.org
  selector:
    matchLabels:
      app: istio-ingressgateway
---
# Source: search-server/templates/envoyFilter.yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: search-server-envoy-filter
  namespace: dev
spec:
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        routeConfiguration:
          vhost:
            name: search-server.dev.curieo.org:80
      patch:
        operation: MERGE
        value:
          name: envoy.ext_authz_disabled
          typed_per_filter_config:
            envoy.filters.http.ext_authz:
              '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
              disabled: true
---
# Source: search-server/templates/Gateway.yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: search-server-gateway
  namespace: dev
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - search-server.dev.curieo.org
      port:
        name: http
        number: 80
        protocol: HTTP
---
# Source: search-server/templates/secretProviderClass.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: search-server
  namespace: dev
spec:
  provider: aws
  secretObjects:
    - secretName: search-server
      type: Opaque
      data:
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
        - objectName: DB_USERNAME
          key: DB_USERNAME
  parameters:
    region: eu-central-1
    objects: |
      - objectName: rds!db-69faccbe-cb63-415d-b424-5b27d0629590 
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "DB_USERNAME"
          - path: "password"
            objectAlias: "DB_PASSWORD"
---
# Source: search-server/templates/virtualservice.yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: search-server-virtualservice
  namespace: dev
spec:
  gateways:
    - search-server-gateway
  hosts:
    - search-server.dev.curieo.org
  http:
    - match:
        - port: 80
      route:
        - destination:
            host: istio-ingressgateway.istio-system.svc.cluster.local
            port:
              number: 80
