# Default values for search-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  image: 698471419283.dkr.ecr.eu-central-1.amazonaws.com/curieo-search-server:1.0
  replica_count: 1
  port: 3030
  aws_account_number: 698471419283
  aws_iam_role: search-server-k8s-service-iam-role
  aws_secret_name: "rds!db-69faccbe-cb63-415d-b424-5b27d0629590"
  dns_zone: dev.curieo.org

database:
  host: curieo-db-1.cjgu6u6kc9e8.eu-central-1.rds.amazonaws.com
  port: "5432"

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    memory: 512Mi
    cpu: 1