version: '3.8'

services:
  web:
    build: api
    ports:
    - 8000:8000
    volumes:
      - ./api:/usr/src/app
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app

  db:
    image: postgres:14-alpine
    ports:
    - 5432:5432
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
