version: "3.8"

services:
  agency:
    build: agency
    ports:
      - 8000:80
    volumes:
      - ./agency:/usr/src/app
    networks:
      - curieo_db
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

  server:
    build: server
    restart: always
    ports:
      - 3030:3030
    networks:
      - curieo_db
    volumes:
      - ./server:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

  frontend:
    build: frontend
    restart: always
    ports:
      - 3000:3000
    networks:
      - curieo_db
    volumes:
      - ./frontend:/usr/src/app

  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432/tcp
    networks:
      curieo_db:
        aliases:
          - curieo_db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=aact
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  cache:
    image: redis:alpine
    ports:
      - 6379:6379/tcp
    networks:
      curieo_db:
        aliases:
          - curieo_cache
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  curieo_db:
