wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.16.4
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710398888.0
    t:
      1:
      - 35
      - 49
      - 51
      - 53
      - 55
      - 95
      - 105
      2:
      - 35
      - 49
      - 51
      - 53
      - 55
      - 95
      - 105
      3:
      - 2
      - 13
      - 23
      4: 3.11.6
      5: 0.16.4
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
