apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: search-{{ .Release.Name }}
  name: search-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.service.replica_count }}
  selector:
    matchLabels:
      app: search-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: search-{{ .Release.Name }}
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-configmap
        image: {{ .Values.service.image }}
        imagePullPolicy: Always
        name: search-{{ .Release.Name }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
