apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - search.{{ .Values.service.dns_zone }}
      port:
        name: https
        number: 443
        protocol: HTTP
