apiVersion: v1
kind: Service
metadata:
  name: search-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http-web
  selector:
    app: {{ .Release.Name }}
  sessionAffinity: "ClientIP"