apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-virtualservice
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
    - {{ .Release.Name }}-gateway
  hosts:
    - {{ .Release.Name }}.{{ .Values.service.dns_zone }}
  http:
    - match:
        - port: 443
      route:
        - destination:
            host: search-{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port }}
