# %%
import requests
from tqdm import tqdm
import pandas as pd 
import json 
#%%
df = pd.read_csv("chembl_eval_data.csv")

#%%
chembl_data_debug = pd.DataFrame()
for i in tqdm(df.iterrows()): 
    url = f"http://127.0.0.1:8000/search?query={i[1]['Question']}"
    data_store = {
        "question": i[1]['Question'],
        "answer": i[1]['Answer'], 
        "study": i[1]['Study Title'],
    }
    payload = {}
    headers = {
    'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjdXJpZW8iLCJqdGkiOiI2ZmI2MTEyNS1jZGU1LTQ2MDAtYWE2MS1jMjBiYzEwNmRhNDMiLCJ0eXBlIjoiYWNjZXNzIiwiZnJlc2giOmZhbHNlLCJpYXQiOjE3MTA3NjUzMDYsImV4cCI6MTcxMDc2NjIwNi4yNzg4Mzd9.nmuzrzmr81ulI8TDauwx19QvLHFi8nXJeUgrEVzfhXs'
    }
    tries = 0
    while tries < 1: 
        try: 
            response = requests.request("GET", url, headers=headers, data=payload)
            json_str = response.text.replace("'", '"').strip('"')
            data = json.loads(json_str)
            if len(data['results']) > 0:
                data_store['refined_results'] = data['result']
                break
        except: 
            tries += 1 
            continue
    if data_store.get("refined_results", None) is not None:
        chembl_data_debug = pd.concat([chembl_data_debug, pd.DataFrame([data_store])], ignore_index=  True )
    else: 
        data_store['refined_results'] = ""
        chembl_data_debug = pd.concat([chembl_data_debug, pd.DataFrame([data_store])], ignore_index= True)

chembl_data_debug.to_csv("chembl_data_debug_source.csv", index = False)


#%%
# chembl data parsing. 
import pandas as pd 
import openai 
#%%
data = [
{'question': 'What is the value of alogP for Paracetamol (Acetaminophen)?', 'table_context_str': 'schema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'drug\']\nsummary: All values are text and in lower case.\n\n\nschema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}, {\'tag\': \'molecule_synonym\', \'properties\': []], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}, {\'tag\': \'synonym_of\', \'properties\': []}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\', \'(synonym:molecule_synonym)-[synonym_edge:synonym_of]->(drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'synonym\']\nsummary: All values are text and in lower case.\n\n\nschema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}, {\'tag\': \'similar_to\', \'properties\': [\'similarity\']}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\', \'(drug:compound_details)-[similarity_edge:similar_to]->(similar_drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'similar_drug\', \'similarity_edge\']\nsummary: All values are text and in lower case.\n', 'cypher_query': '[\'MATCH (input:`molecule_name`)-[:has_parent]->(drug:`compound_details`)\\nWHERE id(input) == "paracetamol"\\nRETURN drug.`compound_details`.`alogP`;\']', 'cypher_response': 'drug.compound_details.alogP : []\n', 'response':'The value of alogP for Paracetamol (Acetaminophen) is not available in the database.'},
{'question': 'What is the alogP value for Aspirin?', 'table_context_str': 'schema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'drug\']\nsummary: All values are text and in lower case.\n\n\nschema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}, {\'tag\': \'similar_to\', \'properties\': [\'similarity\']}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\', \'(drug:compound_details)-[similarity_edge:similar_to]->(similar_drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'similar_drug\', \'similarity_edge\']\nsummary: All values are text and in lower case.\n\n\nschema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}, {\'tag\': \'molecule_synonym\', \'properties\': []], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}, {\'tag\': \'synonym_of\', \'properties\': []}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\', \'(synonym:molecule_synonym)-[synonym_edge:synonym_of]->(drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'synonym\']\nsummary: All values are text and in lower case.\n', 'cypher_query': '[\'MATCH (input:`molecule_name`)-[edge_name:has_parent]->(drug:`compound_details`)\\nWHERE id(input) == "aspirin"\\nRETURN drug.`compound_details`.`alogp`;\']', 'cypher_response': "drug.compound_details.alogp : ['1.31']\n", 'response':'The alogP value for Aspirin is 1.31.'},
{'question': 'Has Aspirin received a black box warning from the FDA?', 'table_context_str': 'schema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'drug\']\nsummary: All values are text and in lower case.\n\n\nschema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}, {\'tag\': \'similar_to\', \'properties\': [\'similarity\']}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\', \'(drug:compound_details)-[similarity_edge:similar_to]->(similar_drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'similar_drug\', \'similarity_edge\']\nsummary: All values are text and in lower case.\n\n\nschema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}, {\'tag\': \'molecule_synonym\', \'properties\': []], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}, {\'tag\': \'synonym_of\', \'properties\': []}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\', \'(synonym:molecule_synonym)-[synonym_edge:synonym_of]->(drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'synonym\']\nsummary: All values are text and in lower case.\n', 'cypher_query': '[\'MATCH (input:`molecule_name`)-[edge_name:has_parent]->(drug:`compound_details`)\\nWHERE id(input) == "aspirin" AND drug.`compound_details`.`fda_warning` == "black box"\\nRETURN drug\']', 'cypher_response': 'drug : []\n', 'response':'As of the current data, there are no records indicating that Aspirin has received a black box warning from the FDA.'},
{'question': 'How many aromatic rings are present in the Aspirin molecule?', 'table_context_str': 'schema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'drug\']\nsummary: All values are text and in lower case.\n\n\nschema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}, {\'tag\': \'similar_to\', \'properties\': [\'similarity\']}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\', \'(drug:compound_details)-[similarity_edge:similar_to]->(similar_drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'similar_drug\', \'similarity_edge\']\nsummary: All values are text and in lower case.\n\n\nschema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}, {\'tag\': \'molecule_synonym\', \'properties\': []], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}, {\'tag\': \'synonym_of\', \'properties\': []}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\', \'(synonym:molecule_synonym)-[synonym_edge:synonym_of]->(drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'synonym\']\nsummary: All values are text and in lower case.\n', 'cypher_query': '[\'MATCH (input:`molecule_name`)-[:has_parent]->(drug:`compound_details`)\\nWHERE id(input) == "aspirin"\\nRETURN drug.full_molecular_formula;\']', 'cypher_response': 'drug.full_molecular_formula : [__NULL__]\n', 'response':'The query did not return any information about the number of aromatic rings present in the Aspirin molecule. It is possible that the specific information about the aromatic rings in Aspirin is not available in the database queried.'},
{'question': 'How many aromatic rings are present in the structure of Aspirin?', 'table_context_str': 'schema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'drug\']\nsummary: All values are text and in lower case.\n\n\nschema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}, {\'tag\': \'similar_to\', \'properties\': [\'similarity\']}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\', \'(drug:compound_details)-[similarity_edge:similar_to]->(similar_drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'similar_drug\', \'similarity_edge\']\nsummary: All values are text and in lower case.\n\n\nschema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}, {\'tag\': \'molecule_synonym\', \'properties\': []], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}, {\'tag\': \'synonym_of\', \'properties\': []}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\', \'(synonym:molecule_synonym)-[synonym_edge:synonym_of]->(drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'synonym\']\nsummary: All values are text and in lower case.\n', 'cypher_query': '[]', 'cypher_response': '', 'response':'The query results did not provide information on the number of aromatic rings present in the structure of Aspirin.'},
{'question': 'What is the molecular type of Paracetamol (Acetaminophen)?', 'table_context_str': 'schema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}, {\'tag\': \'molecule_synonym\', \'properties\': []], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}, {\'tag\': \'synonym_of\', \'properties\': []}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\', \'(synonym:molecule_synonym)-[synonym_edge:synonym_of]->(drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'synonym\']\nsummary: All values are text and in lower case.\n\n\nschema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'drug\']\nsummary: All values are text and in lower case.\n\n\nschema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}, {\'tag\': \'similar_to\', \'properties\': [\'similarity\']}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\', \'(drug:compound_details)-[similarity_edge:similar_to]->(similar_drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'similar_drug\', \'similarity_edge\']\nsummary: All values are text and in lower case.\n', 'cypher_query': '[\'MATCH (input:`molecule_name`)-[edge_name:has_parent]->(drug:`compound_details`)\\nWHERE id(input) == "paracetamol"\\nRETURN drug.`compound_details`.`molecule_type`;\']', 'cypher_response': 'drug.compound_details.molecule_type : []\n', 'response':'The query did not return any specific information about the molecular type of Paracetamol (Acetaminophen). It is possible that the database does not have this information available or that the query was not structured correctly to retrieve it. Additional research or a different query may be needed to find the molecular type of Paracetamol.'},
{'question': 'What is the chirality of Paracetamol (Acetaminophen)?', 'table_context_str': 'schema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'drug\']\nsummary: All values are text and in lower case.\n\n\nschema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}, {\'tag\': \'molecule_synonym\', \'properties\': []], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}, {\'tag\': \'synonym_of\', \'properties\': []}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\', \'(synonym:molecule_synonym)-[synonym_edge:synonym_of]->(drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'synonym\']\nsummary: All values are text and in lower case.\n\n\nschema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}, {\'tag\': \'similar_to\', \'properties\': [\'similarity\']}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\', \'(drug:compound_details)-[similarity_edge:similar_to]->(similar_drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'similar_drug\', \'similarity_edge\']\nsummary: All values are text and in lower case.\n', 'cypher_query': '[\'MATCH (input:`molecule_name`)-[edge_name:has_parent]->(drug:`compound_details`)\\nWHERE id(input) == "paracetamol"\\nRETURN drug.`compound_details`.`chirality`;\']', 'cypher_response': 'drug.compound_details.chirality : []\n', 'response':'The chirality of Paracetamol (Acetaminophen) is not specified in the query results.'},
{'question': 'What is the alogp value for Paracetamol (Acetaminophen)?', 'table_context_str': 'schema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'drug\']\nsummary: All values are text and in lower case.\n\n\nschema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}, {\'tag\': \'molecule_synonym\', \'properties\': []], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}, {\'tag\': \'synonym_of\', \'properties\': []}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\', \'(synonym:molecule_synonym)-[synonym_edge:synonym_of]->(drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'synonym\']\nsummary: All values are text and in lower case.\n\n\nschema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}, {\'tag\': \'similar_to\', \'properties\': [\'similarity\']}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\', \'(drug:compound_details)-[similarity_edge:similar_to]->(similar_drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'similar_drug\', \'similarity_edge\']\nsummary: All values are text and in lower case.\n', 'cypher_query': '[\'MATCH (input:`molecule_name`)-[edge_name:has_parent]->(drug:`compound_details`)\\nWHERE id(input) == "paracetamol"\\nRETURN drug.`compound_details`.`alogp`;\']', 'cypher_response': 'drug.compound_details.alogp : []\n', 'response':'The ALOGP value for Paracetamol (Acetaminophen) is not available in the database.'},
{'question': 'How many aromatic rings are present in the structure of Paracetamol (Acetaminophen)?', 'table_context_str': 'schema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'drug\']\nsummary: All values are text and in lower case.\n\n\nschema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}, {\'tag\': \'similar_to\', \'properties\': [\'similarity\']}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\', \'(drug:compound_details)-[similarity_edge:similar_to]->(similar_drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'similar_drug\', \'similarity_edge\']\nsummary: All values are text and in lower case.\n\n\nschema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}, {\'tag\': \'molecule_synonym\', \'properties\': []], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}, {\'tag\': \'synonym_of\', \'properties\': []}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\', \'(synonym:molecule_synonym)-[synonym_edge:synonym_of]->(drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'synonym\']\nsummary: All values are text and in lower case.\n', 'cypher_query': '[]', 'cypher_response': '', 'response':'The Cypher query did not specifically retrieve information about the number of aromatic rings present in the structure of Paracetamol (Acetaminophen). However, the query did return the molecule name and canonical SMILES notation for Paracetamol. To determine the number of aromatic rings in the structure, further analysis of the SMILES notation or a more specific query targeting the aromatic ring structure would be needed.'},
{'question': 'What is the value of alogP for Paracetamol (Acetaminophen)?', 'table_context_str': 'schema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'drug\']\nsummary: All values are text and in lower case.\n\n\nschema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}, {\'tag\': \'molecule_synonym\', \'properties\': []], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}, {\'tag\': \'synonym_of\', \'properties\': []}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\', \'(synonym:molecule_synonym)-[synonym_edge:synonym_of]->(drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'synonym\']\nsummary: All values are text and in lower case.\n\n\nschema: Node Properties: [{\'tag\': \'compound_details\', \'properties\': [\'molecule_name\', \'molecule_type\', \'first_approval\', \'max_phase\', \'full_weight\', \'full_molecular_formula\', \'standard_inchi\', \'standard_inchi_key\', \'canonical_smiles\']}, {\'tag\': \'molecule_name\', \'properties\': []}], Edge Properties: [{\'tag\': \'has_parent\', \'properties\': []}, {\'tag\': \'similar_to\', \'properties\': [\'similarity\']}], Relationships: [\'(input: molecule_name)-[edge_name:has_parent]->(drug:compound_details)\', \'(drug:compound_details)-[similarity_edge:similar_to]->(similar_drug:compound_details)\'], Where Conditions: [\'id(input) == "drug name"\'], Return Elements: [\'similar_drug\', \'similarity_edge\']\nsummary: All values are text and in lower case.\n', 'cypher_query': '[\'MATCH (input:`molecule_name`)-[:has_parent]->(drug:`compound_details`)\\nWHERE id(input) == "paracetamol"\\nRETURN drug.`compound_details`.`alogP`;\']', 'cypher_response': 'drug.compound_details.alogP : []\n', 'response':'The value of alogP for Paracetamol (Acetaminophen) is not available in the database.'},
]


# %%
chembl_data = pd.DataFrame.from_records(data)
# %%
chembl_data
# %%
ragas_data = pd.DataFrame()
ragas_data['question'] = chembl_data['question']
def get_context(cypher_query, cypher_response): 

    response_synthesis_prompt_str = (
            "Given an input question, synthesize a response from the query results.\n"
            "Cypher Query: {cypher_query}\n"
            "Cypher Response: {context_str}\n"
            "Response: "
        )
    return response_synthesis_prompt_str.format(cypher_query = cypher_query, context_str = cypher_response)


ragas_data['contexts'] = chembl_data[['cypher_query', 'cypher_response']].apply(lambda x: get_context(x[0],x[1]), axis = 1)
ragas_data['answer'] = chembl_data['response']
# %%
eval_data = pd.read_csv("chebml_eval_data.csv")
# %%
# %%
# ragas_data['ground_truth'] = eval_data['Answer']
# %%
# %%
ragas_data
# %%
merged_data = pd.merge(ragas_data, eval_data, left_on= 'question', right_on="Question")
# %%
ragas_data = merged_data[['question', 'contexts', 'answer', 'Answer']]
ragas_data.rename(columns = {'Answer': 'ground_truth'}, inplace = True)
ragas_data.to_csv("ragas_data_chembl.csv", index = False )

# %%
