host = "0.0.0.0"
port = 3030

[search]
max_query_length = 300
max_sources = 10
max_search_context = 5

[summarizer]
model = ""
max_new_tokens = 1024
temperature = 1.0
top_p = 0.7

[openai]
api_url = "https://api.openai.com/v1/chat/completions"
model = "gpt-4o"

[query_rephraser]
model = "mistralai/Mistral-7B-Instruct-v0.2"
max_tokens = 100

[llm]
toxicity_threshold = 0.75

[pubmed]
url_prefix = "https://pubmed.ncbi.nlm.nih.gov"

[brave]
url = "https://api.search.brave.com/res/v1/web/search"
count = 10
result_filter = "query,web"
search_lang = "en"
extra_snippets = true
safesearch = "strict"

[log]
level = "debug"
format = "pretty"

[[oauth2_clients]]
