host = "0.0.0.0"
port = 3030
max_search_query_length = 255

[llm]
top_k_sources = 10
toxicity_threshold = 0.75

[pubmed]
url_prefix = "https://pubmed.ncbi.nlm.nih.gov"

[brave]
url = "https://api.search.brave.com/res/v1/web/search"
count = 10
result_filter = "query,web"
search_lang = "en"
extra_snippets = true
safesearch = "strict"

[log]
level = "debug"
format = "pretty"

[[oauth2_clients]]
