db = "postgresql://postgres:postgres@localhost/curieo_search"
agency_api = "http://127.0.0.1:50051"
oauth2_clients = []

[cache]
url = "redis://127.0.0.1/"
max_sorted_size = 100
enabled = true
ttl = 3600

[log]
level = "info"
format = "json"
