db = "postgresql://postgres:postgres@localhost/curieo_search"
agency_api = "http://127.0.0.1:50051"
oauth2_clients = []
opentelemetry_collector = "http://localhost:4317"

[llm]
prompt_compression_url = "http://localhost:8000/compress"
toxicity_url = "http://localhost:8082/predict"

[summarizer]
api_url = "http://localhost:8001/generate_stream"

[query_rephraser]
api_url = "https://api.together.xyz/inference"

[cache]
url = "redis://127.0.0.1/"
max_sorted_size = 100
enabled = true
ttl = 3600

[log]
level = "info"
format = "json"
