db = "postgresql://postgres:postgres@localhost/curieo_search"
agency_api = "http://127.0.0.1:50051"
oauth2_clients = []

[llm]
bio_llm_url = "http://localhost:8001/generate"
llm_lingua_url = "http://localhost:8000/compress"

[cache]
url = "redis://127.0.0.1/"
max_sorted_size = 100
enabled = true
ttl = 3600

[log]
level = "info"
format = "json"
