db = "postgresql://postgres:postgres@localhost/curieo"
cache_url = "redis://127.0.0.1/"
cache_max_sorted_size = 100
cache_enabled = true
cache_ttl = 3600
rag_api = "http://127.0.0.1:8000"
rag_api_username = "curieo"
rag_api_password = "curieo"
oauth2_clients = []

[log]
level = "info"
format = "json"
