db = "postgresql://postgres:postgres@localhost/curieo"
rag_api = "http://127.0.0.1:8000"
rag_api_username = "curieo"
rag_api_password = "curieo"
oauth2_clients = []

[cache]
cache_url = "redis://127.0.0.1/"
max_sorted_size = 100
enabled = true
ttl = 3600

[log]
level = "info"
format = "json"
