apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.service.replica_count }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: DB_USERNAME
              name: {{ .Release.Name }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: {{ .Release.Name }}
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: DB_HOST
              name: {{ .Release.Name }}
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: DB_PORT
              name: {{ .Release.Name }}
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: DB_NAME
              name: {{ .Release.Name }}
        - name: DB
          value: postgresql://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)
        - name: DATABASE_URL
          value: postgresql://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)
        - name: BRAVE__SUBSCRIPTION_KEY
          valueFrom:
            secretKeyRef:
              key: BRAVE__SUBSCRIPTION_KEY
              name: {{ .Release.Name }}
        - name: BRAVE__GOGGLES_ID
          valueFrom:
            secretKeyRef:
              key: BRAVE__GOGGLES_ID
              name: {{ .Release.Name }}
        - name: LLM__TOXICITY_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: LLM__TOXICITY_AUTH_TOKEN
              name: {{ .Release.Name }}
        - name: QUERY_REPHRASER__API_KEY
          valueFrom:
            secretKeyRef:
              key: QUERY_REPHRASER__API_KEY
              name: {{ .Release.Name }}
        - name: OPENAI__API_KEY
          valueFrom:
            secretKeyRef:
              key: OPENAI__API_KEY
              name: {{ .Release.Name }}
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              key: SENTRY_DSN
              name: {{ .Release.Name }}
        - name: AGENCY_API
          valueFrom:
            secretKeyRef:
              key: AGENCY_API
              name: {{ .Release.Name }}
        - name: LLM__PROMPT_COMPRESSION_URL
          valueFrom:
            secretKeyRef:
              key: LLM__PROMPT_COMPRESSION_URL
              name: {{ .Release.Name }}
        - name: LLM__TOXICITY_URL
          valueFrom:
            secretKeyRef:
              key: LLM__TOXICITY_URL
              name: {{ .Release.Name }}
        - name: SUMMARIZER__API_URL
          valueFrom:
            secretKeyRef:
              key: SUMMARIZER__API_URL
              name: {{ .Release.Name }}
        - name: QUERY_REPHRASER__API_URL
          valueFrom:
            secretKeyRef:
              key: QUERY_REPHRASER__API_URL
              name: {{ .Release.Name }}
        - name: CACHE__URL
          valueFrom:
            secretKeyRef:
              key: CACHE__URL
              name: {{ .Release.Name }}
        image: {{ .Values.service.image }}
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP
        name: {{ .Release.Name }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}