apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  secretObjects:
    - secretName: {{ .Release.Name }}
      type: Opaque
      data:
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
        - objectName: DB_USERNAME
          key: DB_USERNAME
  parameters:
    region: eu-central-1
    objects: |
      - objectName: {{ .Values.service.aws_secret_name }} 
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "DB_USERNAME"
          - path: "password"
            objectAlias: "DB_PASSWORD"
