apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  secretObjects:
    - secretName: {{ .Release.Name }}
      type: Opaque
      data:
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
        - objectName: DB_USERNAME
          key: DB_USERNAME
        - objectName: DB_HOST
          key: DB_HOST
        - objectName: DB_PORT
          key: DB_PORT
        - objectName: DB_NAME
          key: DB_NAME
        - objectName: OPENTELEMETRY_COLLECTOR
          key: OPENTELEMETRY_COLLECTOR
        - objectName: BRAVE__SUBSCRIPTION_KEY
          key: BRAVE__SUBSCRIPTION_KEY
        - objectName: BRAVE__GOGGLES_ID
          key: BRAVE__GOGGLES_ID
        - objectName: LLM__TOXICITY_AUTH_TOKEN
          key: LLM__TOXICITY_AUTH_TOKEN
        - objectName: QUERY_REPHRASER__API_KEY
          key: QUERY_REPHRASER__API_KEY
        - objectName: OPENAI__API_KEY
          key: OPENAI__API_KEY
        - objectName: SENTRY_DSN
          key: SENTRY_DSN
        - objectName: AGENCY_API
          key: AGENCY_API
        - objectName: LLM__PROMPT_COMPRESSION_URL
          key: LLM__PROMPT_COMPRESSION_URL
        - objectName: LLM__TOXICITY_URL
          key: LLM__TOXICITY_URL
        - objectName: SUMMARIZER__API_URL
          key: SUMMARIZER__API_URL
        - objectName: QUERY_REPHRASER__API_URL
          key: QUERY_REPHRASER__API_URL
        - objectName: CACHE__URL
          key: CACHE__URL
  parameters:
    region: eu-central-1
    objects: |
      - objectName: {{ .Values.service.aws_rds_secret_name }}
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "DB_USERNAME"
          - path: "password"
            objectAlias: "DB_PASSWORD"
      - objectName: {{ .Values.service.deployment_envs_secret_name }}
        objectType: "secretsmanager"
        jmesPath:
          - path: "BRAVE__SUBSCRIPTION_KEY"
            objectAlias: "BRAVE__SUBSCRIPTION_KEY"
          - path: "BRAVE__GOGGLES_ID"
            objectAlias: "BRAVE__GOGGLES_ID"
          - path: "LLM__TOXICITY_AUTH_TOKEN"
            objectAlias: "LLM__TOXICITY_AUTH_TOKEN"
          - path: "QUERY_REPHRASER__API_KEY"
            objectAlias: "QUERY_REPHRASER__API_KEY"
          - path: "OPENAI__API_KEY"
            objectAlias: "OPENAI__API_KEY"
          - path: "SENTRY_DSN"
            objectAlias: "SENTRY_DSN"
          - path: "AGENCY_API"
            objectAlias: "AGENCY_API"
          - path: "LLM__PROMPT_COMPRESSION_URL"
            objectAlias: "LLM__PROMPT_COMPRESSION_URL"
          - path: "LLM__TOXICITY_URL"
            objectAlias: "LLM__TOXICITY_URL"
          - path: "SUMMARIZER__API_URL"
            objectAlias: "SUMMARIZER__API_URL"
          - path: "QUERY_REPHRASER__API_URL"
            objectAlias: "QUERY_REPHRASER__API_URL"
          - path: "CACHE__URL"
            objectAlias: "CACHE__URL"
          - path: "DB_NAME"
            objectAlias: "DB_NAME"
          - path: "DB_HOST"
            objectAlias: "DB_HOST"
          - path: "DB_PORT"
            objectAlias: "DB_PORT"
          - path: "OPENTELEMETRY_COLLECTOR"
            objectAlias: "OPENTELEMETRY_COLLECTOR"