apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # Needed to grant your app an access to AWS resources
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{.Values.service.aws_account_number}}:role/{{.Values.service.aws_iam_role}}"
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}