# Default values for search-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  image: 698471419283.dkr.ecr.eu-central-1.amazonaws.com/curieo-agency:latest
  replica_count: 1
  port: 50051

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    memory: 512Mi
    cpu: 1