version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8000:80
    networks:
      - curieo_db
    depends_on:
      db:
        condition: service_healthy
    links:
    - db

  db:
    image: postgres:14-alpine
    ports:
    - 5432:5432/tcp
    networks:
      curieo_db:
        aliases:
          - curieo_db
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_DB=aact
    - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  curieo_db:
