name: Agency CI
on:
  workflow_call:

defaults:
  run:
    working-directory: agency

jobs:
  tests-and-linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.8.3"
          virtualenvs-create: true
          virtualenvs-in-project: true

      - uses: actions/setup-python@v5
        with:
          cache: "poetry"
          python-version-file: "agency/.python-version"

      - name: Install dependencies
        run: poetry install

      - name: Linting & formatting
        run: make lint & make fmt-check

      - name: Run tests
        run: make test


