name: CI

on: push

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings"
  RUSTUP_MAX_RETRIES: 10

jobs:
  detect-changes:
    name: Detect file changes
    runs-on: ubuntu-latest
    timeout-minutes: 3
    # Map a step output to a job output
    outputs:
      agency: ${{ steps.changes.outputs.agency }}
      frontend: ${{ steps.changes.outputs.frontend }}
      llmlingua_service: ${{ steps.changes.outputs.llmlingua_service }}
      proto: ${{ steps.changes.outputs.proto }}
      server: ${{ steps.changes.outputs.server }}
    steps:
      - uses: actions/checkout@v4

      - name: Find changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yaml

  agency:
    if: needs.detect-changes.outputs.agency == 'true'
    needs: detect-changes
    uses: ./.github/workflows/agency.yaml

  server:
    if: needs.detect-changes.outputs.server == 'true'
    needs: detect-changes
    uses: ./.github/workflows/server.yaml