name: Python tests

on:
  push:

defaults:
  run:
    working-directory: backend

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: ls -la
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          cache: "poetry"
          python-version-file: "backend/.python-version"

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASS: postgres
          DB_BASE: db_test
        run: poetry run pytest
